# Generated by Django 6.1.1 on 2026-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='plantilla',
            field=models.CharField(choices=[('A', 'A — Elegante'), ('B', 'B — Moderna'), ('C', 'C — Link en bio'), ('default', 'default (alias de C)')], default='C', max_length=32),
        ),
    ]
