# Generated by Django 6.1.1 on 2026-09-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_alter_tarjeta_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='profesion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
