# Generated by Django 6.1.1 on 2026-09-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_tarjeta_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_ultimo_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
