# Generated by Django 6.1.1 on 2026-09-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0004_tarjeta_fecha_ultimo_pago_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_ultimo_aviso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
