# Generated by Django 6.1.1 on 2026-09-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0005_tarjeta_fecha_ultimo_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_terras', models.PositiveIntegerField(default=5)),
                ('dias_suscripcion', models.PositiveIntegerField(default=30)),
                ('dias_aviso_previo', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
            ],
            options={
                'verbose_name': 'Estadísticas',
                'verbose_name_plural': 'Estadísticas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tarjetas.tarjeta',),
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_terras', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tarjetas.tarjeta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
