# Generated by Django 6.1.1 on 2026-09-10 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0007_configuraciontarjetas_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='mostrar_faq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mostrar_noticias',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mostrar_testimonios',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='tarjetas.tarjeta')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tarjetas.tarjeta')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('autor', models.CharField(max_length=255)),
                ('relacion', models.CharField(blank=True, max_length=255, null=True)),
                ('texto', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='tarjetas.tarjeta')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden'],
            },
        ),
    ]
