# Generated by Django 6.1.1 on 2026-09-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0008_tarjeta_mostrar_faq_tarjeta_mostrar_noticias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='precio_pro_clp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='flow_order',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='medio',
            field=models.CharField(default='terras', max_length=16),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='monto_clp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='monto_terras',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
