# Generated by Django 6.1.1 on 2026-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0009_configuraciontarjetas_precio_pro_clp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='plantilla',
            field=models.CharField(choices=[('A', 'A — Elegante'), ('B', 'B — Moderna'), ('C', 'C — Link en bio'), ('default', 'default (alias de C)'), ('pro_min', 'Pro — Minimalista'), ('pro_mod', 'Pro — Moderna'), ('pro_corp', 'Pro — Corporativa'), ('pro_calido', 'Pro — Cálida'), ('pro_dark', 'Pro — Oscura Premium'), ('pro_editorial', 'Pro — Editorial')], default='C', max_length=32),
        ),
    ]
