# Generated by Django 6.1.1 on 2026-10-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0010_alter_tarjeta_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='anual_meses_pagados',
            field=models.PositiveSmallIntegerField(default=10, help_text='Meses que se pagan en el plan anual (12 meses de servicio).'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='descuento_semestral_pct',
            field=models.PositiveSmallIntegerField(default=10, help_text='Descuento (%) del plan semestral sobre 6 × precio mensual.'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='fundador_cupos',
            field=models.PositiveIntegerField(default=100, help_text='Cupos totales del plan Fundador.'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='fundador_dias_gracia',
            field=models.PositiveSmallIntegerField(default=5, help_text='Días tras vencer en que el fundador aún conserva su precio preferente.'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='fundador_meses',
            field=models.PositiveSmallIntegerField(default=6, help_text='Meses que da el plan Fundador.'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='fundador_precio_clp',
            field=models.PositiveIntegerField(default=9000, help_text='Pago único del plan Fundador.'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='fundador_renovacion_meses',
            field=models.PositiveSmallIntegerField(default=24, help_text='Meses que rige el precio de renovación del fundador.'),
        ),
        migrations.AddField(
            model_name='configuraciontarjetas',
            name='fundador_renovacion_precio_clp',
            field=models.PositiveIntegerField(default=3500, help_text='Precio base mensual del fundador tras sus meses de fundador.'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='fundador_precio_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='numero_fundador',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OrdenPagoPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=64, unique=True)),
                ('plan', models.CharField(choices=[('fundador', 'Fundador'), ('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=16)),
                ('meses', models.PositiveSmallIntegerField()),
                ('monto_clp', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=16)),
                ('mp_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pago', to='tarjetas.tarjeta')),
            ],
            options={
                'verbose_name': 'Orden de pago Pro',
                'verbose_name_plural': 'Órdenes de pago Pro',
                'ordering': ['-creado'],
            },
        ),
    ]
