# Generated by Django 6.1.1 on 2026-10-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0012_precio_base_pro_5000'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='tarjeta_ref',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='tarjetas.tarjeta'),
        ),
    ]
