# Generated by Django 6.1.1 on 2026-10-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0014_pagos_completar_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='plantilla',
            field=models.CharField(choices=[('A', 'A — Elegante'), ('B', 'B — Moderna'), ('C', 'C — Link en bio'), ('default', 'default (alias de C)'), ('pro_min', 'Pro — Minimalista'), ('pro_mod', 'Pro — Moderna'), ('pro_corp', 'Pro — Corporativa'), ('pro_calido', 'Pro — Cálida'), ('pro_dark', 'Pro — Oscura Premium'), ('pro_editorial', 'Pro — Editorial'), ('serena', 'Pro — Serena (belleza)'), ('confianza', 'Pro — Confianza (oficios)'), ('vacio', 'Pro — Vacío (moderna oscura)'), ('revista', 'Pro — Revista (editorial)')], default='C', max_length=32),
        ),
    ]
