# Generated by Django 6.1.1 on 2026-10-08 02:50

import apps.tarjetas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0015_plantillas_tanda1'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[apps.tarjetas.models.validar_anio_producto]),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_clp',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a 0.'), django.core.validators.MaxValueValidator(99999999, message='El precio no puede superar $99.999.999.')]),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_desde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='zonas_cobertura',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300, message='Las zonas no pueden superar los 300 caracteres.')]),
        ),
    ]
