# Generated by Django 6.1.1 on 2026-10-08 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0016_productos_precio_zonas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='mostrar_pasos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='plantilla',
            field=models.CharField(choices=[('A', 'A — Elegante'), ('B', 'B — Moderna'), ('C', 'C — Link en bio'), ('default', 'default (alias de C)'), ('pro_min', 'Pro — Minimalista'), ('pro_mod', 'Pro — Moderna'), ('pro_corp', 'Pro — Corporativa'), ('pro_calido', 'Pro — Cálida'), ('pro_dark', 'Pro — Oscura Premium'), ('pro_editorial', 'Pro — Editorial'), ('serena', 'Pro — Serena (belleza)'), ('confianza', 'Pro — Confianza (oficios)'), ('vacio', 'Pro — Vacío (moderna oscura)'), ('revista', 'Pro — Revista (editorial)'), ('pausa', 'Pro — Pausa (salud)'), ('huella', 'Pro — Huella (mascotas)'), ('lustre', 'Pro — Lustre (lujo metálico)'), ('mosaico', 'Pro — Mosaico (bento)'), ('balance', 'Pro — Balance (consultoría)'), ('miga', 'Pro — Miga (comida por encargo)'), ('forma', 'Pro — Forma (talleres)'), ('tinta', 'Pro — Tinta (eventos)')], default='C', max_length=32),
        ),
        migrations.CreateModel(
            name='PasoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('texto', models.TextField(validators=[django.core.validators.MaxLengthValidator(200, message='El texto no puede superar los 200 caracteres.')])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='tarjetas.tarjeta')),
            ],
            options={
                'verbose_name': 'Paso de "Cómo funciona"',
                'verbose_name_plural': 'Pasos de "Cómo funciona"',
                'ordering': ['orden'],
            },
        ),
    ]
